init = true

[[entry]]
path = "example"
interval = 5
exclude = ["^.*\\.sw(?:p|x|px)$"]
command = [
    "echo 'example'"
]

[[entry]]
path = "src"
interval = 7
command = [
	"echo 'src'"
]

[[entry]]
path = "target"
recursive = true
interval = 9
exclude = ["^\\."]
command = [
	"echo 'target'"
]
