init = true
verbose = true

# [[entry]]
# path = "."
# interval = 5
# exclude = ["^.*\\.sw(?:p|x|px)$"]
# command = [
# 	"echo \"term: $TERM\" >> example/logfile.log"
# ]

[[entry]]
path = "example"
recursive = true
interval = 30
command = [
    "echo wela",
    # "cat example/logfile.log"
]
