[package]
name = "watchd"
version = "0.1.0"
authors = ["Davide Casella <davide@comedia.it>"]
edition = "2018"

[dependencies]
clap = "2"
notify = "4"
regex = "1"
serde = "1"
serde_derive = "1"
slog = "2.4"
slog-scope = "4.1"
sloggers = "0.3"
toml = "0.4"
