init = true

[[entry]]
path = "examples"
delay = 5
exclude = ["^.*\\.sw(?:p|x|px)$"]
command = [
    "printf 'examples' >&2"
]

[[entry]]
path = "src"
command = [
	"printf 'src'"
]

[[entry]]
path = "target"
recursive = true
delay = 9
exclude = ["^\\."]
command = [
	"printf 'target'"
]
