init = true

[[entry]]
path = "examples"
delay = 5
exclude = ["^.*\\.sw(?:p|x|px)$"]
command = [
    "echo 'examples' >&2"
]

[[entry]]
path = "src"
delay = 0
command = [
	"echo 'src'"
]

[[entry]]
path = "target"
recursive = true
delay = 9
exclude = ["^\\."]
command = [
	"echo 'target'"
]
